apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "5000"

spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
      - name: flask-app
        image: cmpfl0w/my-flask-app:latest
        env:
          - name: SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: flask-secret
                key: SECRET_KEY
          - name: EMAIL_USER
            valueFrom:
              secretKeyRef:
                name: flask-secret
                key: EMAIL_USER
          - name: SENDGRID_API_KEY
            valueFrom:
              secretKeyRef:
                name: flask-secret
                key: SENDGRID_API_KEY

        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        - containerPort: 8000 

