name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
permissions:
      id-token: write
      contents: read
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest

    - name: Run tests
      run: |
        pytest -v tests/

  docker_build:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Log in to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      run: |
        MAGE_TAG=$(date +%s)  # Use timestamp for unique tag
        docker build -t ${{ secrets.DOCKER_USERNAME }}/my-flask-app:$IMAGE_TAG .
        docker push ${{ secrets.DOCKER_USERNAME }}/my-flask-app:$IMAGE_TAG
        echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV

  deploy:
    runs-on: ubuntu-latest
    
    needs: docker_build
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    
      
    - name: Set up AWS CLI
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_DEFAULT_REGION }}
    
    - name: Update kubeconfig
      run: aws eks update-kubeconfig --region us-east-1 --name web-quickstart
        
    - name: Deploy to Kubernetes
      run: |
        kubectl set image deployment/your-deployment your-container=${{ secrets.DOCKER_USERNAME }}/my-flask-app:$IMAGE_TAG
